# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f11fa9d2b8cc837d2f41cdc7c54bce741415fd6910e5ee2f9f913624a4fad097fa68c8f37552596ec1eae29bf4fa06b5ac1dfcaa9cd181f0c840ae08353d1eb2

test:
  secret_key_base: 2dcb3ce00ea350019521f1b8458504fc4fb2bbc2266807f71fba2730f0fe1df74d990c3448ff5730c34173265a6f4a34cc1a3ce3b112f8bd7c5327de8553dfa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
